// Test: Expression parsing - binary, unary, sizeof, etc.
#include "../testing_utility.h"

const Cn_String src = CN_STR_BUFFER(
    "int test_binary_ops(int a, int b) {\n"
    "    int x;\n"
    "    x = a + b;\n"
    "    x = a - b;\n"
    "    x = a * b;\n"
    "    x = a / b;\n"
    "    x = a % b;\n"
    "    x = a & b;\n"
    "    x = a | b;\n"
    "    x = a ^ b;\n"
    "    x = a << 2;\n"
    "    x = a >> 2;\n"
    "    return x;\n"
    "}\n"
    "\n"
    "int test_comparison(int a, int b) {\n"
    "    if (a == b) return 1;\n"
    "    if (a != b) return 2;\n"
    "    if (a < b) return 3;\n"
    "    if (a > b) return 4;\n"
    "    if (a <= b) return 5;\n"
    "    if (a >= b) return 6;\n"
    "    return 0;\n"
    "}\n"
    "\n"
    "int test_logical(int a, int b) {\n"
    "    if (a && b) return 1;\n"
    "    if (a || b) return 2;\n"
    "    if (!a) return 3;\n"
    "    return 0;\n"
    "}\n"
    "\n"
    "int test_unary(int a) {\n"
    "    int x;\n"
    "    x = -a;\n"
    "    x = +a;\n"
    "    x = ~a;\n"
    "    x = !a;\n"
    "    return x;\n"
    "}\n"
    "\n"
    "int test_sizeof(void) {\n"
    "    int x;\n"
    "    x = sizeof(int);\n"
    "    x = sizeof(x);\n"
    "    x = sizeof(int *);\n"
    "    return x;\n"
    "}\n"
    "\n"
    "int test_ternary(int a) {\n"
    "    return a > 0 ? 1 : -1;\n"
    "}\n"
    "\n"
    "int test_assignment(void) {\n"
    "    int x = 10;\n"
    "    x += 5;\n"
    "    x -= 3;\n"
    "    x *= 2;\n"
    "    x /= 2;\n"
    "    x %= 3;\n"
    "    x &= 0xFF;\n"
    "    x |= 0x10;\n"
    "    x ^= 0x01;\n"
    "    x <<= 1;\n"
    "    x >>= 1;\n"
    "    return x;\n"
    "}\n"
);

int main(void) {
    cn_diagnostic_handler = &cn_test_diagnostic_handler;

    Cn_Translation_Unit tu = cn_tu_make("input.i", .source = src);
    cn_tu_process(&tu, CN_NO_CODE_OUTPUT);
    cn_tu_free(&tu);

    return 0;
}
