// Test: Attribute specifiers - C style [[...]] and GNU style __attribute__((...))
#include "../testing_utility.h"

const Cn_String src = CN_STR_BUFFER(
    /* --- [[...]] on external declarations and definitions ---------------- */
    "[[note]] int attributed_global;\n"
    "[[note]] static int attributed_static_global = 1;\n"
    "[[]] int empty_attribute_global;\n"
    "[[first]] [[second]] int two_specifiers_global;\n"
    "[[first, second]] int two_attributes_global;\n"
    "[[note(1)]] int attribute_with_argument;\n"
    "[[note(1, 2, 3)]] int attribute_with_arguments;\n"
    "[[note(\"text\")]] int attribute_with_string_argument;\n"
    "[[vendor::note]] int namespaced_attribute_global;\n"
    "[[vendor::note(42)]] int namespaced_attribute_with_argument;\n"
    "\n"
    "[[note]] int attributed_declaration(int x);\n"
    "\n"
    "[[note]] int attributed_function(int x) {\n"
    "    return x;\n"
    "}\n"
    "\n"
    "[[note]] struct AttributedStructUser {\n"
    "    int x;\n"
    "} attributed_struct_global;\n"
    "\n"
    /* --- [[...]] on statements ------------------------------------------- */
    "int test_attributes_on_statements(int x) {\n"
    "    [[note]] int local = 0;\n"
    "    [[note]] local = x;\n"
    "    [[note]] ;\n"
    "\n"
    "    [[note]] {\n"
    "        local = local + 1;\n"
    "    }\n"
    "\n"
    "    [[note]] if (x > 0) {\n"
    "        local = 1;\n"
    "    } else {\n"
    "        local = 2;\n"
    "    }\n"
    "\n"
    "    [[note]] switch (x) {\n"
    "        default:\n"
    "            local = 3;\n"
    "            break;\n"
    "    }\n"
    "\n"
    "    [[note]] while (local > 0) {\n"
    "        [[note]] break;\n"
    "    }\n"
    "\n"
    "    [[note]] do {\n"
    "        [[note]] continue;\n"
    "    } while (0);\n"
    "\n"
    "    [[note]] for ([[note]] int i = 0; i < x; i = i + 1) {\n"
    "        local = local + i;\n"
    "    }\n"
    "\n"
    "    [[note]] goto finish;\n"
    "\n"
    "    [[note]] finish:\n"
    "    [[note]] return local;\n"
    "}\n"
    "\n"
    "int test_multiple_attributes_on_statement(int x) {\n"
    "    [[first]] [[second]] x = x + 1;\n"
    "    [[first, second]] x = x + 1;\n"
    "    [[vendor::note(1)]] x = x + 1;\n"
    "    return x;\n"
    "}\n"
    "\n"
    /* --- [[...]] on enums ------------------------------------------------ */
    "enum [[note]] AttributedEnum {\n"
    "    AE_A [[note]],\n"
    "    AE_B [[note]] = 5,\n"
    "    AE_C [[vendor::note(1)]],\n"
    "    AE_D [[first, second]]\n"
    "};\n"
    "\n"
    /* --- GNU __attribute__((...)) ---------------------------------------- */
    "__attribute__((unused)) int gnu_leading_global;\n"
    "int gnu_trailing_global __attribute__((unused));\n"
    "int gnu_two_specifiers __attribute__((unused)) __attribute__((deprecated));\n"
    "int gnu_two_attributes __attribute__((unused, deprecated));\n"
    "int gnu_attribute_with_argument __attribute__((aligned(16)));\n"
    "int gnu_attribute_with_string __attribute__((section(\"mysection\")));\n"
    "__attribute__((unused)) static int gnu_static_global;\n"
    "\n"
    "__attribute__((unused)) int gnu_attributed_declaration(int x);\n"
    "\n"
    "__attribute__((unused)) int gnu_attributed_function(int x) {\n"
    "    return x;\n"
    "}\n"
    "\n"
    "struct __attribute__((packed)) GnuPackedStruct {\n"
    "    int x;\n"
    "    int y __attribute__((aligned(8)));\n"
    "};\n"
    "\n"
    "union __attribute__((packed)) GnuPackedUnion {\n"
    "    int i;\n"
    "    float f;\n"
    "};\n"
    "\n"
    "enum __attribute__((unused)) GnuAttributedEnum {\n"
    "    GAE_A __attribute__((unused)),\n"
    "    GAE_B __attribute__((deprecated)) = 2\n"
    "};\n"
    "\n"
    "int test_gnu_attributes_on_locals(int x) {\n"
    "    __attribute__((unused)) int a = 0;\n"
    "    int b __attribute__((unused)) = 0;\n"
    "    return x + a + b;\n"
    "}\n"
    "\n"
    /* --- both styles combined -------------------------------------------- */
    "[[note]] __attribute__((unused)) int mixed_leading_global;\n"
    "[[note]] int mixed_trailing_global __attribute__((unused));\n"
    "\n"
    "[[note]] __attribute__((unused)) int test_mixed_attributes(int x) {\n"
    "    [[note]] __attribute__((unused)) int local = x;\n"
    "    return local;\n"
    "}\n"
);

int main(void) {
    cn_diagnostic_handler = &cn_test_diagnostic_handler;
    Cn_Translation_Unit tu = {0};
    cn_tu_init(&tu, "input.i", .source = src, .flags = CN_TU_NO_CODE_OUTPUT);
    cn_tu_process(&tu);
    cn_tu_free(&tu);
    return 0;
}
