// Test: Switch statement with case and default labels
#include "../testing_utility.h"

const Cn_String src = CN_STR_BUFFER(
    "int test_switch(int x) {\n"
    "    int r = 0;\n"
    "    switch (x) {\n"
    "        case 0:\n"
    "            r = 1;\n"
    "            break;\n"
    "        case 1:\n"
    "        case 2:\n"
    "            r = 2;\n"
    "            break;\n"
    "        case 3 + 4:\n"
    "            r = 3;\n"
    "            break;\n"
    "        default:\n"
    "            r = -1;\n"
    "            break;\n"
    "    }\n"
    "    return r;\n"
    "}\n"
    "\n"
    "int test_switch_fallthrough(int x) {\n"
    "    int r = 0;\n"
    "    switch (x) {\n"
    "        case 0:\n"
    "            r = r + 1;\n"
    "        case 1:\n"
    "            r = r + 2;\n"
    "        default:\n"
    "            r = r + 3;\n"
    "    }\n"
    "    return r;\n"
    "}\n"
    "\n"
    "int test_switch_default_first(int x) {\n"
    "    int r;\n"
    "    switch (x) {\n"
    "        default:\n"
    "            r = 0;\n"
    "            break;\n"
    "        case 5:\n"
    "            r = 5;\n"
    "            break;\n"
    "    }\n"
    "    return r;\n"
    "}\n"
    "\n"
    "int test_switch_empty_body(int x) {\n"
    "    switch (x) {\n"
    "    }\n"
    "    return x;\n"
    "}\n"
    "\n"
    "int test_switch_no_block(int x) {\n"
    "    int r = 0;\n"
    "    switch (x)\n"
    "        case 0:\n"
    "            r = 1;\n"
    "    return r;\n"
    "}\n"
    "\n"
    "int test_switch_declaration_in_body(int x) {\n"
    "    int r = 0;\n"
    "    switch (x) {\n"
    "        int local;\n"
    "        case 0:\n"
    "            local = 7;\n"
    "            r = local;\n"
    "            break;\n"
    "    }\n"
    "    return r;\n"
    "}\n"
    "\n"
    "int test_nested_switch(int x, int y) {\n"
    "    int r = 0;\n"
    "    switch (x) {\n"
    "        case 0:\n"
    "            switch (y) {\n"
    "                case 0:\n"
    "                    r = 1;\n"
    "                    break;\n"
    "                default:\n"
    "                    r = 2;\n"
    "                    break;\n"
    "            }\n"
    "            break;\n"
    "        default:\n"
    "            r = 3;\n"
    "            break;\n"
    "    }\n"
    "    return r;\n"
    "}\n"
    "\n"
    "int test_switch_expression_condition(int a, int b) {\n"
    "    int r = 0;\n"
    "    switch (a + b * 2) {\n"
    "        case 0:\n"
    "            r = 1;\n"
    "            break;\n"
    "    }\n"
    "    switch ((a)) {\n"
    "        case 0:\n"
    "            r = 2;\n"
    "            break;\n"
    "    }\n"
    "    return r;\n"
    "}\n"
    "\n"
    "int test_switch_constant_case_labels(int x) {\n"
    "    int r = 0;\n"
    "    switch (x) {\n"
    "        case sizeof(int):\n"
    "            r = 1;\n"
    "            break;\n"
    "        case 1 << 4:\n"
    "            r = 2;\n"
    "            break;\n"
    "        case -1:\n"
    "            r = 3;\n"
    "            break;\n"
    "    }\n"
    "    return r;\n"
    "}\n"
);

int main(void) {
    cn_diagnostic_handler = &cn_test_diagnostic_handler;
    Cn_Translation_Unit tu = cn_tu_make("input.i", .source = src);
    cn_tu_process(&tu, CN_NO_CODE_OUTPUT);
    cn_tu_free(&tu);
    return 0;
}
