// Test: goto statement and identifier labels
#include "../testing_utility.h"

const Cn_String src = CN_STR_BUFFER(
    "int test_goto_forward(int x) {\n"
    "    if (x > 0) goto done;\n"
    "    x = -x;\n"
    "done:\n"
    "    return x;\n"
    "}\n"
    "\n"
    "int test_goto_backward(int x) {\n"
    "again:\n"
    "    x = x - 1;\n"
    "    if (x > 0) goto again;\n"
    "    return x;\n"
    "}\n"
    "\n"
    "int test_multiple_labels(int x) {\n"
    "    if (x == 0) goto zero;\n"
    "    if (x == 1) goto one;\n"
    "    goto other;\n"
    "zero:\n"
    "    return 0;\n"
    "one:\n"
    "    return 1;\n"
    "other:\n"
    "    return x;\n"
    "}\n"
    "\n"
    "int test_label_on_empty_statement(int x) {\n"
    "    goto end;\n"
    "end:\n"
    "    ;\n"
    "    return x;\n"
    "}\n"
    "\n"
    "int test_label_on_block(int x) {\n"
    "    goto body;\n"
    "body:\n"
    "    {\n"
    "        x = x + 1;\n"
    "    }\n"
    "    return x;\n"
    "}\n"
    "\n"
    "int test_chained_labels(int x) {\n"
    "    goto second;\n"
    "first:\n"
    "second:\n"
    "third:\n"
    "    return x;\n"
    "}\n"
    "\n"
    "int test_label_inside_nested_block(int x) {\n"
    "    {\n"
    "        {\n"
    "            if (x > 0) goto inner;\n"
    "inner:\n"
    "            x = x + 1;\n"
    "        }\n"
    "    }\n"
    "    return x;\n"
    "}\n"
    "\n"
    "int test_goto_out_of_loop(int n) {\n"
    "    int sum = 0;\n"
    "    for (int i = 0; i < n; i = i + 1) {\n"
    "        for (int j = 0; j < n; j = j + 1) {\n"
    "            if (i * j > 10) goto finished;\n"
    "            sum = sum + 1;\n"
    "        }\n"
    "    }\n"
    "finished:\n"
    "    return sum;\n"
    "}\n"
    "\n"
    "int test_goto_into_same_name_label(int x) {\n"
    "    goto again;\n"
    "again:\n"
    "    return x;\n"
    "}\n"
    "\n"
    "int test_label_on_loop(int x) {\n"
    "loop_head:\n"
    "    while (x > 0) {\n"
    "        x = x - 1;\n"
    "        if (x == 3) goto loop_head;\n"
    "    }\n"
    "    return x;\n"
    "}\n"
);

int main(void) {
    cn_diagnostic_handler = &cn_test_diagnostic_handler;
    Cn_Translation_Unit tu = {0};
    cn_tu_init(&tu, "input.i", .source = src, .flags = CN_TU_NO_CODE_OUTPUT);
    cn_tu_process(&tu);
    cn_tu_free(&tu);
    return 0;
}
