// Test: break and continue jump statements
#include "../testing_utility.h"

const Cn_String src = CN_STR_BUFFER(
    "int test_break_in_while(int x) {\n"
    "    while (x > 0) {\n"
    "        if (x == 5) break;\n"
    "        x = x - 1;\n"
    "    }\n"
    "    return x;\n"
    "}\n"
    "\n"
    "int test_continue_in_while(int x) {\n"
    "    int sum = 0;\n"
    "    while (x > 0) {\n"
    "        x = x - 1;\n"
    "        if (x == 5) continue;\n"
    "        sum = sum + x;\n"
    "    }\n"
    "    return sum;\n"
    "}\n"
    "\n"
    "int test_break_continue_in_do_while(int x) {\n"
    "    int sum = 0;\n"
    "    do {\n"
    "        x = x - 1;\n"
    "        if (x == 3) continue;\n"
    "        if (x == 0) break;\n"
    "        sum = sum + x;\n"
    "    } while (x > 0);\n"
    "    return sum;\n"
    "}\n"
    "\n"
    "int test_break_continue_in_for(int n) {\n"
    "    int sum = 0;\n"
    "    for (int i = 0; i < n; i = i + 1) {\n"
    "        if (i == 1) continue;\n"
    "        if (i == 2) break;\n"
    "        sum = sum + i;\n"
    "    }\n"
    "    return sum;\n"
    "}\n"
    "\n"
    "int test_break_in_switch(int x) {\n"
    "    int r = 0;\n"
    "    switch (x) {\n"
    "        default:\n"
    "            r = 1;\n"
    "            break;\n"
    "    }\n"
    "    return r;\n"
    "}\n"
    "\n"
    "int test_break_continue_without_block(int n) {\n"
    "    int sum = 0;\n"
    "    for (int i = 0; i < n; i = i + 1)\n"
    "        if (i == 2) break;\n"
    "    while (n > 0) {\n"
    "        n = n - 1;\n"
    "        if (n) continue;\n"
    "        else break;\n"
    "    }\n"
    "    return sum;\n"
    "}\n"
    "\n"
    "int test_break_continue_in_nested_loops(int n) {\n"
    "    int sum = 0;\n"
    "    for (int i = 0; i < n; i = i + 1) {\n"
    "        for (int j = 0; j < n; j = j + 1) {\n"
    "            if (j == i) continue;\n"
    "            if (j > 3) break;\n"
    "            sum = sum + 1;\n"
    "        }\n"
    "        if (sum > 100) break;\n"
    "    }\n"
    "    while (n > 0) {\n"
    "        do {\n"
    "            n = n - 1;\n"
    "            if (n == 1) break;\n"
    "        } while (n > 0);\n"
    "        if (n == 0) break;\n"
    "        continue;\n"
    "    }\n"
    "    return sum;\n"
    "}\n"
    "\n"
    "int test_break_continue_in_nested_blocks(int n) {\n"
    "    while (n > 0) {\n"
    "        {\n"
    "            {\n"
    "                n = n - 1;\n"
    "                if (n == 3) continue;\n"
    "                if (n == 1) break;\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "    return n;\n"
    "}\n"
);

int main(void) {
    cn_diagnostic_handler = &cn_test_diagnostic_handler;
    Cn_Translation_Unit tu = {0};
    cn_tu_init(&tu, "input.i", .source = src, .flags = CN_TU_NO_CODE_OUTPUT);
    cn_tu_process(&tu);
    cn_tu_free(&tu);
    return 0;
}
