// Test: Iteration statements - while, do while, for
#include "../testing_utility.h"

const Cn_String src = CN_STR_BUFFER(
    "int test_while(int x) {\n"
    "    while (x > 0) {\n"
    "        x = x - 1;\n"
    "    }\n"
    "    return x;\n"
    "}\n"
    "\n"
    "int test_while_no_block(int x) {\n"
    "    while (x > 0)\n"
    "        x = x - 1;\n"
    "    return x;\n"
    "}\n"
    "\n"
    "int test_while_empty_body(int x) {\n"
    "    while (x > 0)\n"
    "        ;\n"
    "    while (x > 0) {\n"
    "    }\n"
    "    return x;\n"
    "}\n"
    "\n"
    "int test_while_complex_condition(int a, int b) {\n"
    "    while (a > 0 && b > 0) {\n"
    "        a = a - 1;\n"
    "        b = b - 1;\n"
    "    }\n"
    "    while (a) {\n"
    "        a = 0;\n"
    "    }\n"
    "    return a + b;\n"
    "}\n"
    "\n"
    "int test_nested_while(int x, int y) {\n"
    "    int r = 0;\n"
    "    while (x > 0) {\n"
    "        while (y > 0) {\n"
    "            r = r + 1;\n"
    "            y = y - 1;\n"
    "        }\n"
    "        x = x - 1;\n"
    "    }\n"
    "    return r;\n"
    "}\n"
    "\n"
    "int test_do_while(int x) {\n"
    "    do {\n"
    "        x = x + 1;\n"
    "    } while (x < 5);\n"
    "    return x;\n"
    "}\n"
    "\n"
    "int test_do_while_no_block(int x) {\n"
    "    do\n"
    "        x = x + 1;\n"
    "    while (x < 5);\n"
    "    return x;\n"
    "}\n"
    "\n"
    "int test_do_while_empty_body(int x) {\n"
    "    do {\n"
    "    } while (0);\n"
    "    do ; while (0);\n"
    "    return x;\n"
    "}\n"
    "\n"
    "int test_nested_do_while(int x) {\n"
    "    int y = 0;\n"
    "    do {\n"
    "        do {\n"
    "            y = y + 1;\n"
    "        } while (y < 3);\n"
    "        x = x - 1;\n"
    "    } while (x > 0);\n"
    "    return y;\n"
    "}\n"
    "\n"
    "int test_for(int n) {\n"
    "    int sum = 0;\n"
    "    int i;\n"
    "    for (i = 0; i < n; i = i + 1) {\n"
    "        sum = sum + i;\n"
    "    }\n"
    "    return sum;\n"
    "}\n"
    "\n"
    "int test_for_declaration_init(int n) {\n"
    "    int sum = 0;\n"
    "    for (int i = 0; i < n; i = i + 1) {\n"
    "        sum = sum + i;\n"
    "    }\n"
    "    for (int i = 0, j = n; i < j; i = i + 1, j = j - 1) {\n"
    "        sum = sum + 1;\n"
    "    }\n"
    "    return sum;\n"
    "}\n"
    "\n"
    "int test_for_omitted_clauses(int n) {\n"
    "    int i = 0;\n"
    "    int sum = 0;\n"
    "    for (; i < n; i = i + 1) {\n"
    "        sum = sum + 1;\n"
    "    }\n"
    "    for (i = 0; ; i = i + 1) {\n"
    "        break;\n"
    "    }\n"
    "    for (i = 0; i < n;) {\n"
    "        i = i + 1;\n"
    "    }\n"
    "    for (;;) {\n"
    "        break;\n"
    "    }\n"
    "    for (;;)\n"
    "        break;\n"
    "    return sum;\n"
    "}\n"
    "\n"
    "int test_for_no_block(int n) {\n"
    "    int sum = 0;\n"
    "    for (int i = 0; i < n; i = i + 1)\n"
    "        sum = sum + i;\n"
    "    for (int i = 0; i < n; i = i + 1)\n"
    "        ;\n"
    "    return sum;\n"
    "}\n"
    "\n"
    "int test_for_comma_clauses(int n) {\n"
    "    int i, j, sum = 0;\n"
    "    for (i = 0, j = n; i < j; i = i + 1, j = j - 1) {\n"
    "        sum = sum + 1;\n"
    "    }\n"
    "    return sum;\n"
    "}\n"
    "\n"
    "int test_nested_for(int n) {\n"
    "    int sum = 0;\n"
    "    for (int i = 0; i < n; i = i + 1) {\n"
    "        for (int j = 0; j < n; j = j + 1) {\n"
    "            sum = sum + i * j;\n"
    "        }\n"
    "    }\n"
    "    return sum;\n"
    "}\n"
    "\n"
    "int test_mixed_loops(int n) {\n"
    "    int sum = 0;\n"
    "    for (int i = 0; i < n; i = i + 1) {\n"
    "        int j = i;\n"
    "        while (j > 0) {\n"
    "            do {\n"
    "                j = j - 1;\n"
    "            } while (0);\n"
    "        }\n"
    "        sum = sum + j;\n"
    "    }\n"
    "    return sum;\n"
    "}\n"
    "\n"
    "int test_loop_scoped_declarations(int n) {\n"
    "    int sum = 0;\n"
    "    for (int i = 0; i < n; i = i + 1) {\n"
    "        int local = i * 2;\n"
    "        sum = sum + local;\n"
    "    }\n"
    "    while (sum > 0) {\n"
    "        int local = sum;\n"
    "        sum = local - 1;\n"
    "    }\n"
    "    return sum;\n"
    "}\n"
);

int main(void) {
    cn_diagnostic_handler = &cn_test_diagnostic_handler;
    Cn_Translation_Unit tu = cn_tu_make("input.i", .source = src);
    cn_tu_process(&tu, CN_NO_CODE_OUTPUT);
    cn_tu_free(&tu);
    return 0;
}
