// Test: Enum specifiers, enumerators and enum constants
#include "../testing_utility.h"

const Cn_String src = CN_STR_BUFFER(
    "enum Color {\n"
    "    RED,\n"
    "    GREEN,\n"
    "    BLUE,\n"
    "};\n"
    "\n"
    "enum Explicit {\n"
    "    E_ONE = 1,\n"
    "    E_TWO = 2,\n"
    "    E_TEN = 10,\n"
    "};\n"
    "\n"
    "enum Mixed {\n"
    "    M_ZERO,\n"
    "    M_FIVE = 5,\n"
    "    M_SIX,\n"
    "    M_SEVEN,\n"
    "};\n"
    "\n"
    "enum Computed {\n"
    "    C_A = 1,\n"
    "    C_B = C_A + 1,\n"
    "    C_C = C_A | C_B,\n"
    "    C_D = 1 << 4,\n"
    "    C_E = sizeof(int),\n"
    "    C_F = -1,\n"
    "};\n"
    "\n"
    "enum Trailing {\n"
    "    T_A,\n"
    "    T_B,\n"
    "};\n"
    "\n"
    "enum Single { S_ONLY, };\n"
    "\n"
    "enum {\n"
    "    ANON_A = 10,\n"
    "    ANON_B,\n"
    "};\n"
    "\n"
    "typedef enum Season {\n"
    "    WINTER,\n"
    "    SPRING,\n"
    "    SUMMER,\n"
    "    AUTUMN,\n"
    "} Season;\n"
    "\n"
    "typedef enum {\n"
    "    STATE_IDLE,\n"
    "    STATE_RUNNING,\n"
    "} State;\n"
    "\n"
    "enum Fixed : unsigned int {\n"
    "    FX_A,\n"
    "    FX_B,\n"
    "};\n"
    "\n"
    "enum Color global_color;\n"
    "enum Color global_color_init = GREEN;\n"
    "Season global_season = SPRING;\n"
    "State global_state = STATE_IDLE;\n"
    "enum Fixed : unsigned int global_fixed;\n"
    "\n"
    "int color_table[BLUE + 1];\n"
    "int anon_table[ANON_B];\n"
    "static const int const_from_enum = E_TEN * 2;\n"
    "\n"
    "enum Color test_enum_return(void) {\n"
    "    return RED;\n"
    "}\n"
    "\n"
    "int test_enum_parameter(enum Color c, Season s) {\n"
    "    return c + s;\n"
    "}\n"
    "\n"
    "int test_enum_locals(void) {\n"
    "    enum Color local = BLUE;\n"
    "    enum Mixed m = M_SEVEN;\n"
    "    Season s = AUTUMN;\n"
    "    State st = STATE_RUNNING;\n"
    "\n"
    "    enum Local {\n"
    "        L_A,\n"
    "        L_B = 3\n"
    "    };\n"
    "    enum Local l = L_B;\n"
    "\n"
    "    return local + m + s + st + l;\n"
    "}\n"
    "\n"
    "int test_enum_constants_in_expressions(int x) {\n"
    "    int r;\n"
    "    r = RED + GREEN + BLUE;\n"
    "    r = x > 0 ? E_ONE : E_TWO;\n"
    "    r = C_C & C_D;\n"
    "    r = (int)ANON_A;\n"
    "    if (x == BLUE) r = 1;\n"
    "    return r;\n"
    "}\n"
    "\n"
    "int test_sizeof_enum(void) {\n"
    "    int x;\n"
    "    x = sizeof(enum Color);\n"
    "    x = sizeof(Season);\n"
    "    x = sizeof(RED);\n"
    "    return x;\n"
    "}\n"
    "\n"
    "struct WithEnum {\n"
    "    enum Color color;\n"
    "    Season season;\n"
    "    enum Inner {\n"
    "        IN_A,\n"
    "        IN_B,\n"
    "    } inner;\n"
    "};\n"
    "\n"
    "int test_enum_member_access(struct WithEnum *w) {\n"
    "    w->color = RED;\n"
    "    w->inner = IN_B;\n"
    "    return w->color + w->inner;\n"
    "}\n"
    "\n"
    "int test_enum_array_initializer(void) {\n"
    "    int values[3] = { RED, GREEN, BLUE, };\n"
    "    return values[0];\n"
    "}\n"
);

int main(void) {
    cn_diagnostic_handler = &cn_test_diagnostic_handler;
    Cn_Translation_Unit tu = {0};
    cn_tu_init(&tu, "input.i", .source = src, .flags = CN_TU_NO_CODE_OUTPUT);
    cn_tu_process(&tu);
    cn_tu_free(&tu);
    return 0;
}
